# Declare the board's master clock
#create_clock -name sys_clk -period 10.0 -waveform {0 5} [get_ports clk]

# Applying a Timing Exception #####################################################################
#set_false_path -from [get_pins {GEN_ROS_MAIN[*].RO_inst/aux_i_inferred_i_1/O}] -to [get_pins {GEN_ROS_MAIN[*].RO_inst/aux_i_inferred_i_6/I1}]
#set_false_path -from [get_pins {GEN_ROS_LFSR[*].RO_inst/aux_i_inferred_i_1/O}] -to [get_pins {GEN_ROS_LFSR[*].RO_inst/aux_i_inferred_i_6/I1}]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -hierarchical -filter {NAME =~ *GEN_ROS_MAIN[*].RO_inst/aux_i[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -hierarchical -filter {NAME =~ *GEN_ROS_LFSR[*].RO_inst/aux_i[5]}]

set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *GEN_ROS_MAIN*RO_inst}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *GEN_ROS_LFSR*RO_inst}]

#set_property DONT_TOUCH true [get_cells -hierarchical *ro_map_inst*]
#set_property DONT_TOUCH true [get_cells -hierarchical *comparator_inst*]

# Placement (ro_placement.py) #####################################################################

# GEN_ROS_MAIN[0]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y148 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y148 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[1]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y146 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y146 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[2]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y144 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y144 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[3]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y142 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y142 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[4]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y140 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y140 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[5]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y138 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y138 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[6]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y136 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y136 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[7]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y134 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y134 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[0]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y98 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y98 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[1]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y96 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y96 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[2]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y94 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y94 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[3]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y92 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y92 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[4]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y90 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y90 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[5]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y88 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y88 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[6]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y86 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y86 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[7]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y84 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y84 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[8]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y82 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y82 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[9]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y80 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y80 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_6}]
