# Declare the board's master clock
#create_clock -name sys_clk -period 10.0 -waveform {0 5} [get_ports clk]

# Applying Timing Exceptions ######################################################################

set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *GEN_ROS_MAIN*RO_inst}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *GEN_ROS_LFSR*RO_inst}]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -hierarchical -filter {NAME =~ *.RO_inst/aux_i[5]}]

# GEN_ROS_MAIN[0]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y149 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y148 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y148 [get_cells {GEN_ROS_MAIN[0].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[1]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y147 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y146 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y146 [get_cells {GEN_ROS_MAIN[1].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[2]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y145 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y144 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y144 [get_cells {GEN_ROS_MAIN[2].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[3]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y143 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y142 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y142 [get_cells {GEN_ROS_MAIN[3].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[4]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y141 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y140 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y140 [get_cells {GEN_ROS_MAIN[4].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[5]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y139 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y138 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y138 [get_cells {GEN_ROS_MAIN[5].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[6]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y137 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y136 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y136 [get_cells {GEN_ROS_MAIN[6].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[7]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y135 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y134 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y134 [get_cells {GEN_ROS_MAIN[7].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[8]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y133 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y133 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y133 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y133 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y132 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y132 [get_cells {GEN_ROS_MAIN[8].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[9]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y131 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y131 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y131 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y131 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y130 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y130 [get_cells {GEN_ROS_MAIN[9].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[10]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y129 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y129 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y129 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y129 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y128 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y128 [get_cells {GEN_ROS_MAIN[10].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[11]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y127 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y127 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y127 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y127 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y126 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y126 [get_cells {GEN_ROS_MAIN[11].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[12]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y125 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y125 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y125 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y125 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y124 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y124 [get_cells {GEN_ROS_MAIN[12].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[13]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y123 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y123 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y123 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y123 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y122 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y122 [get_cells {GEN_ROS_MAIN[13].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[14]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y121 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y121 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y121 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y121 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y120 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y120 [get_cells {GEN_ROS_MAIN[14].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[15]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y119 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y119 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y119 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y119 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y118 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y118 [get_cells {GEN_ROS_MAIN[15].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[16]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y117 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y117 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y117 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y117 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y116 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y116 [get_cells {GEN_ROS_MAIN[16].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[17]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y115 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y115 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y115 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y115 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y114 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y114 [get_cells {GEN_ROS_MAIN[17].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[18]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y113 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y113 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y113 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y113 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y112 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y112 [get_cells {GEN_ROS_MAIN[18].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[19]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y111 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y111 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y111 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y111 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y110 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y110 [get_cells {GEN_ROS_MAIN[19].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[20]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y109 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y109 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y109 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y109 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y108 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y108 [get_cells {GEN_ROS_MAIN[20].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[21]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y107 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y107 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y107 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y107 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y106 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y106 [get_cells {GEN_ROS_MAIN[21].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[22]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y105 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y105 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y105 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y105 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y104 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y104 [get_cells {GEN_ROS_MAIN[22].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[23]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y103 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y103 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y103 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y103 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y102 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y102 [get_cells {GEN_ROS_MAIN[23].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[24]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y101 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y101 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y101 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y101 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y100 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y100 [get_cells {GEN_ROS_MAIN[24].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[25]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y149 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y149 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y149 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y149 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y148 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y148 [get_cells {GEN_ROS_MAIN[25].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[26]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y147 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y147 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y147 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y147 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y146 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y146 [get_cells {GEN_ROS_MAIN[26].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[27]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y145 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y145 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y145 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y145 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y144 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y144 [get_cells {GEN_ROS_MAIN[27].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[28]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y143 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y143 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y143 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y143 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y142 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y142 [get_cells {GEN_ROS_MAIN[28].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[29]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y141 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y141 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y141 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y141 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y140 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y140 [get_cells {GEN_ROS_MAIN[29].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[30]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y139 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y139 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y139 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y139 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y138 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y138 [get_cells {GEN_ROS_MAIN[30].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_MAIN[31]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X39Y137 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X39Y137 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X39Y137 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X39Y137 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X39Y136 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X39Y136 [get_cells {GEN_ROS_MAIN[31].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[0]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y99 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y98 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y98 [get_cells {GEN_ROS_LFSR[0].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[1]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y97 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y96 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y96 [get_cells {GEN_ROS_LFSR[1].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[2]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y95 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y94 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y94 [get_cells {GEN_ROS_LFSR[2].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[3]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y93 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y92 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y92 [get_cells {GEN_ROS_LFSR[3].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[4]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y91 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y90 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y90 [get_cells {GEN_ROS_LFSR[4].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[5]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y89 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y88 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y88 [get_cells {GEN_ROS_LFSR[5].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[6]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y87 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y86 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y86 [get_cells {GEN_ROS_LFSR[6].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[7]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y85 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y84 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y84 [get_cells {GEN_ROS_LFSR[7].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[8]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y83 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y82 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y82 [get_cells {GEN_ROS_LFSR[8].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[9]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y81 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y80 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y80 [get_cells {GEN_ROS_LFSR[9].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[10]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y79 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y79 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y79 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y79 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y78 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y78 [get_cells {GEN_ROS_LFSR[10].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[11]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y77 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y77 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y77 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y77 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y76 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y76 [get_cells {GEN_ROS_LFSR[11].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[12]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y75 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y75 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y75 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y75 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y74 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y74 [get_cells {GEN_ROS_LFSR[12].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[13]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y73 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y73 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y73 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y73 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y72 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y72 [get_cells {GEN_ROS_LFSR[13].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[14]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y71 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y71 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y71 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y71 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y70 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y70 [get_cells {GEN_ROS_LFSR[14].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[15]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y69 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y69 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y69 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y69 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y68 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y68 [get_cells {GEN_ROS_LFSR[15].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[16]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y67 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y67 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y67 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y67 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y66 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y66 [get_cells {GEN_ROS_LFSR[16].RO_inst/aux_i_inferred_i_6}]

# GEN_ROS_LFSR[17]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_1}]
set_property LOC SLICE_X37Y65 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_1}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_2}]
set_property LOC SLICE_X37Y65 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_2}]
set_property BEL B6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_3}]
set_property LOC SLICE_X37Y65 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_3}]
set_property BEL A6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_4}]
set_property LOC SLICE_X37Y65 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_4}]
set_property BEL D6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_5}]
set_property LOC SLICE_X37Y64 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_5}]
set_property BEL C6LUT [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_6}]
set_property LOC SLICE_X37Y64 [get_cells {GEN_ROS_LFSR[17].RO_inst/aux_i_inferred_i_6}]

